<?php

namespace AppBundle\Repository;

/**
 * GreetingCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GreetingCommentRepository extends \Doctrine\ORM\EntityRepository
{
}
