<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Greeting;
use Doctrine\ORM\EntityRepository;

/**
 * GreetingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GreetingRepository extends EntityRepository
{
    public function getQueryAllApproved()
    {
        return $this
            ->createQueryBuilder('g')
            ->where('g.status = :status')
            ->setParameter('status', Greeting::STATUS_APPROVED)
            ->orderBy('g.createdAt', 'DESC')
            ;
    }

    public function findAllNonModerated()
    {
        return $this
            ->createQueryBuilder('g')
            ->where('g.status IS NULL')
            ->orWhere('g.status = :status')
            ->setParameter('status', Greeting::STATUS_PENDING)
            ->orderBy('g.createdAt', 'DESC')
            ;
    }
}
