<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Guestbook;
use Doctrine\ORM\EntityRepository;

/**
 * GuestbookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GuestbookRepository extends EntityRepository
{
    public function getQueryAllApproved()
    {
        return $this
            ->createQueryBuilder('g')
            ->where('g.status = :status')
            ->setParameter('status', Guestbook::STATUS_APPROVED)
            ->orderBy('g.createdAt', 'DESC')
        ;
    }

    public function findAllNonModerated()
    {
        return $this
            ->createQueryBuilder('g')
            ->where('g.status IS NULL')
            ->orWhere('g.status = :status')
            ->setParameter('status', Guestbook::STATUS_PENDING)
            ->orderBy('g.createdAt', 'DESC')
        ;
    }

}
