<?php

namespace AppBundle\Repository;

/**
 * GuestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GuestRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByCriteria(array $criteria)
    {
        $qb = $this->createQueryBuilder('g')
        foreach($criteria as $fieldname => $value) {
            if (!empty($value)) {
                if (!in_array($fieldname, array('firstname', 'lastname', 'email')) {
                    throw new \Exception();
                }
             
                if ($fieldname === 'firstname' || $fieldname === 'lastname') {
                    $qb->andWhere($qb->expr()->like('g'.$fieldname, $value));                    
                } else {
                    $qb
                        ->andWhere('g'.$fieldname, ':value')
                        ->setParameter('value', $value)
                    ;
                }
            }
        }
        
        return $qb->getQuery()->getResult();
    }
}
