<?php

namespace AppBundle\Repository;

/**
 * GuestbookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GuestbookRepository extends \Doctrine\ORM\EntityRepository
{
    public function getQueryAllModerate()
    {
        return $this
            ->createQueryBuilder('g')
            ->where('g.moderated = 1')
            ->orderBy('g.date', 'DESC')
        ;
    }

    public function findAllNonModerated()
    {
        return $this
            ->createQueryBuilder('g')
            ->where('g.moderated IS NULL')
            ->orWhere('g.moderated = 0')
            ->orderBy('g.date', 'DESC')
        ;
    }

}
