services:
    admin.guest:
        class: AppBundle\Admin\GuestAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin.group.administration, label: admin.model.guests }
        arguments:
            - ~
            - AppBundle\Entity\Guest
            - AppBundle\Controller\GuestAdminController
        calls:
            - [ setTranslationDomain, [admin]]
        public: true

    admin.greetings:
        class: AppBundle\Admin\GreetingAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin.group.administration, label: admin.model.greetings }
        arguments:
            - ~
            - AppBundle\Entity\Greeting
            - ~
        calls:
            - [ setTranslationDomain, [admin]]
        public: true

    admin.location:
        class: AppBundle\Admin\LocationAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin.group.settings, label: admin.model.locations }
        arguments:
            - ~
            - AppBundle\Entity\Location
            - ~
        calls:
            - [ setTranslationDomain, [admin]]
        public: true
