<?php

namespace AdminBundle\Repository;

use AdminBundle\Entity\Greeting;
use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    public function getQueryAllPublished()
    {
        return $this
            ->createQueryBuilder('p')
            ->where('p.published = :published')
            ->setParameter('published', true)
            ->orderBy('p.publishedAt', 'DESC')
        ;
    }
}
