<?php

namespace AdminBundle\Repository;

/**
 * ReplyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TableRepository extends \Doctrine\ORM\EntityRepository
{
}
