parameters:    
    user.controller.resetting.class: Application\FOS\UserBundle\Controller\ResettingController
    user.controller.security.class: Application\FOS\UserBundle\Controller\SecurityController
    user.listener.registration.class: Application\FOS\UserBundle\EventListener\RegistrationListener
    user.listener.resetting.class: Application\FOS\UserBundle\EventListener\ResettingListener
    user.listener.flash.class: Application\FOS\UserBundle\EventListener\FlashListener
    user.listener.authentication.class: Application\FOS\UserBundle\EventListener\AuthenticationListener

services:
    user.resetting.controller:
        class: "%user.controller.resetting.class%"
        arguments:
            - "@event_dispatcher"
            - "@fos_user.resetting.form.factory"
            - "@fos_user.user_manager"
            - "@fos_user.util.token_generator"
            - "@AppBundle\\Service\\Mailer"
            - "%fos_user.resetting.retry_ttl%"
        public: true
        calls:
            - [setContainer, ["@service_container"]]
            
    user.security.controller:
        class: "%user.controller.security.class%"
        arguments:
            - "@event_dispatcher"
            - "@security.csrf.token_manager"
        public: true
        calls:
            - [setContainer, ["@service_container"]]            

    fos_user.listener.email_confirmation:
        class:        "%user.listener.registration.class%"
        arguments:    ["@AppBundle\\Service\\Mailer", "@fos_user.util.token_generator", "@router", "@session"]
        tags:
            - { name: kernel.event_subscriber }
    
    fos_user.listener.resetting:
        class:        "%user.listener.resetting.class%"
        arguments:    ["@router", "%fos_user.resetting.token_ttl%"]
        tags:
            - { name: kernel.event_subscriber }

    fos_user.listener.flash:
        class:        "%user.listener.flash.class%"
        arguments:    ["@session", "@app.helper.flash_message"]
        tags:
            - { name: kernel.event_subscriber }
            
    fos_user.listener.authentication:
        class:        "%user.listener.authentication.class%"
        arguments:    ["@fos_user.security.login_manager", "%fos_user.firewall_name%"]
        tags:
            - { name: kernel.event_subscriber }            
