parameters:
    user.listener.registration.class: Application\FOS\UserBundle\EventListener\RegistrationListener
    user.listener.resetting.class: Application\FOS\UserBundle\EventListener\ResettingListener
    user.listener.flash.class: Application\FOS\UserBundle\EventListener\FlashListener

services:
    user.resetting.controller:
        class: Application\FOS\UserBundle\Controller\ResettingController
        arguments:
            - "@event_dispatcher"
            - "@fos_user.resetting.form.factory"
            - "@fos_user.user_manager"
            - "@fos_user.util.token_generator"
            - "@AppBundle\\Service\\Mailer"
            - "%fos_user.resetting.retry_ttl%"
        public: true
        calls:
            - [setContainer, ["@service_container"]]

    fos_user.listener.email_confirmation:
        class:        "%user.listener.registration.class%"
        arguments:    ["@AppBundle\\Service\\Mailer", "@fos_user.util.token_generator", "@router", "@session"]
        tags:
            - { name: kernel.event_subscriber }
    
    fos_user.listener.resetting:
        class:        "%user.listener.resetting.class%"
        arguments:    ["@router", "%fos_user.resetting.token_ttl%"]
        tags:
            - { name: kernel.event_subscriber }

    fos_user.listener.flash:
        class:        "%user.listener.flash.class%"
        arguments:    ["@session", "@app.helper.flash_message"]
        tags:
            - { name: kernel.event_subscriber }