parameters:
    user.registration.listener.class: Application\FOS\UserBundle\EventListener\RegistrationListener
    user.registration.form.class: Application\FOS\UserBundle\Form\Type\RegistrationType
    user.resetting.listener.class: Application\FOS\UserBundle\EventListener\ResettingListener

services:
    user.resetting.controller:
        class: Application\FOS\UserBundle\Controller\ResettingController
        arguments:
            - "@event_dispatcher"
            - "@fos_user.resetting.form.factory"
            - "@fos_user.user_manager"
            - "@fos_user.util.token_generator"
            - "@AppBundle\\Service\\Mailer"
            - "%fos_user.resetting.retry_ttl%"
        public: true
        calls:
            - [setContainer, ["@service_container"]]

    user.form.registration:
        class: "%user.registration.form.class%"
        tags:
            - { name: form.type, alias: app_user_registration }

    fos_user.listener.email_confirmation:
        class:        "%user.registration.listener.class%"
        arguments:    ["@AppBundle\\Service\\Mailer", "@fos_user.util.token_generator", "@router", "@session"]
        tags:
            - { name: kernel.event_subscriber }
    
    fos_user.listener.resetting:
        class:        "%user.resetting.listener.class%"
        arguments:    ["@router", "%fos_user.resetting.token_ttl%"]
        tags:
            - { name: kernel.event_subscriber }
