services:
    ogd.admin.guest:
        class: AdminBundle\Admin\GuestAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin.group.administration, label: admin.model.guests }
        arguments:
            - ~
            - AdminBundle\Entity\Guest
            - AdminBundle\Controller\GuestAdminController
        calls:
            - [ setTranslationDomain, [AdminBundle]]
        public: true

    ogd.admin.greetings:
        class: AdminBundle\Admin\GreetingAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin.group.administration, label: admin.model.greetings }
        arguments:
            - ~
            - AdminBundle\Entity\Greeting
            - ~
        calls:
            - [ setTranslationDomain, [AdminBundle]]
        public: true

    ogd.admin.post:
        class: AdminBundle\Admin\PostAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin.group.administration, label: admin.model.posts }
        arguments:
            - ~
            - AdminBundle\Entity\Post
            - ~
        calls:
            - [ setTranslationDomain, [AdminBundle]]
        public: true

    ogd.admin.comment:
        class: AdminBundle\Admin\CommentAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin.group.administration, label: admin.model.comments }
        arguments:
            - ~
            - AdminBundle\Entity\AbstractComment
            - ~
        calls:
            - [ setSubClasses, [{greeting: AdminBundle\Entity\GreetingComment, post: AdminBundle\Entity\PostComment}]]
            - [ setTranslationDomain, [AdminBundle]]
        public: true

    ogd.admin.location:
        class: AdminBundle\Admin\LocationAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin.group.settings, label: admin.model.locations }
        arguments:
            - ~
            - AdminBundle\Entity\Location
            - ~
        calls:
            - [ setTranslationDomain, [AdminBundle]]
        public: true

    ogd.admin.table:
        class: AdminBundle\Admin\TableAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin.group.administration, label: admin.model.tables }
        arguments:
            - ~
            - AdminBundle\Entity\Table
            - ~
        calls:
            - [ setTranslationDomain, [AdminBundle]]
        public: true

    ogd.admin.seat:
        class: AdminBundle\Admin\SeatAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin.group.administration, label: admin.model.seats }
        arguments:
            - ~
            - AdminBundle\Entity\Seat
            - ~
        calls:
            - [ setTranslationDomain, [AdminBundle]]
            - [ setTemplate, [edit, "@Admin/SeatAdmin/edit.html.twig"]]            
        public: true
