# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.helper.flash_message:
        class: AppBundle\Templating\Helper\FlashMessageHelper
        arguments: ["@translator"]
        public: true
        tags:
            - { name: templating.helper }
            
    app.helper.social_url:
        class: AppBundle\Templating\Helper\SocialUrlHelper
        arguments: ["@router"]
        public: true
        tags:
            - { name: templating.helper }

    app.menu.social:
        class: AppBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory", "@app.helper.social_url", "@translator"]
        tags:
            - { name: knp_menu.menu_builder, method: createSocialMenu, alias: social } # The alias is what is used to retrieve the menu    
        
    app.menu.main:
        class: AppBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory", "@app.helper.social_url", "@translator"]
        tags:
            - { name: knp_menu.menu_builder, method: createMainMenu, alias: main } # The alias is what is used to retrieve the menu

    app.validator.guest_exists:
        class: AppBundle\Validator\Constraints\GuestExistsValidator
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: validator.constraint_validator }

    app.listener.maintenance:
        class: AppBundle\Event\Listener\MaintenanceListener
        arguments: ["@service_container"]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }