# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
services:
    ogd.app.helper.flash_message:
        class: AppBundle\Templating\Helper\FlashMessageHelper
        arguments: ["@translator"]
        public: true
        tags:
            - { name: templating.helper }
            
    ogd.app.helper.social_url:
        class: AppBundle\Templating\Helper\SocialUrlHelper
        arguments: ["@router"]
        public: true
        tags:
            - { name: templating.helper }
            
    ogd.app.menu.builder:
        class: AppBundle\Service\MenuBuilder
        arguments: ["@knp_menu.factory", "@translator"]

    ogd.app.menu.main:
        class:  Knp\Menu\MenuItem # the service definition requires setting the class
        factory: ["@app.menu.builder", createMainMenu]
        arguments:
            - "@request_stack"
            - "@security.authorization_checker"
            - "@security.token_storage"
        tags:
            - { name: knp_menu.menu, alias: main } # The alias is what is used to retrieve the menu
            
    ogd.app.menu.social:
        class:  Knp\Menu\MenuItem # the service definition requires setting the class
        factory: ["@ogd.app.menu.builder", createSocialMenu]
        arguments: ["@ogd.app.helper.social_url"]
        tags:
            - { name: knp_menu.menu, alias: social } # The alias is what is used to retrieve the menu

    ogd.app.listener.maintenance:
        class: AppBundle\Event\Listener\MaintenanceListener
        arguments: ["@service_container"]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    ogd.app.mailer:
        alias: AppBundle\Service\Mailer
        public: true
